name: Laravel Deployment

on:
  push:
    branches:
      - main  # Change this to your main branch name, if different

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'  # Change this to your desired PHP version
        extensions: |
          pdo
          pdo_mysql
          # Add any other required PHP extensions

    - name: Install dependencies
      run: composer install --no-dev --prefer-dist --no-scripts --no-progress --no-suggest

    - name: Build assets (if applicable)
      # Add any command to build your assets (e.g., npm run production)

    - name: Deploy to cPanel
      uses: mohit-kumar-s/cpanel-git-deploy@v2
      with:
        cpanel_username: ${{ secrets.CPANEL_USER }}
        cpanel_password: ${{ secrets.CPANEL_PASSWORD }}
        cpanel_domain: fecotrade.dhruboarif.com
        host: ${{ secrets.CPANEL_HOST }}
        key: ${{ secrets.CPANEL_SSH_PRIVATE_KEY }}
        script: 'cd /var/www/html && sh ./.scripts/deploy.sh'
        cpanel_directory: /home/arifulislam/fecotrade.dhruboarif.com/

